Institution="University of yaounde 1"
Faculty="Facsciences"
Departement="Computer Science"
Level="Master 1"
Student="Jorel TIOMELA"
StudentEmail="jorel.tiomela@facsciences-uy1.cm"
Supervisor="Mr Kemtho Paul"